# Generated by Django 4.0.3 on 2022-04-06 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mahasiswa',
            fields=[
                ('nim', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=20)),
                ('alamat', models.CharField(max_length=40)),
                ('tanggal_lahir', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MataKuliah',
            fields=[
                ('kode_mk', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nama_mk', models.CharField(max_length=20)),
                ('sks', models.IntegerField(verbose_name=2)),
            ],
        ),
        migrations.CreateModel(
            name='Perkuliahan',
            fields=[
                ('id_perkuliahan', models.AutoField(primary_key=True, serialize=False)),
                ('nilai', models.FloatField()),
                ('kode_mk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.matakuliah')),
                ('nim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.mahasiswa')),
            ],
        ),
    ]
