# Generated by Django 4.0.3 on 2022-04-06 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matakuliah',
            name='nama_mk',
            field=models.CharField(max_length=30),
        ),
    ]
