# Generated by Django 4.0.4 on 2022-06-22 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_matakuliah_nama_mk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('umur', models.IntegerField()),
            ],
        ),
    ]
