# Generated by Django 4.0.3 on 2022-03-16 04:09

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_userauthentication_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauthentication',
            name='token_expired',
            field=models.DateTimeField(default=authentication.models.expire, null=True),
        ),
    ]
