# Generated by Django 4.0.3 on 2022-03-16 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_userauthentication_token_expired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauthentication',
            name='token',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
