# Generated by Django 4.0.3 on 2022-03-16 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_userauthentication_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrole',
            name='role_id',
        ),
    ]
